export const tc1 = {
  mytitle: 'My Store',
  email: 'imsoumyagupta@gmail.com',
  fname: 'Soumya',
  lname: 'Gupta',
  password: 'Automation@123',
  fn: 'Sona',
  ln: 'Gup',
  company: "Capegimini",
  adress: 'Balagere road',
  city: 'BANGALORE',
  postcode: '00000',
  mobile: '9342147127',
  address2: 'My address',
 t1: 'My Store',
 tc2:'My account - My Store',
 addCartUrl:"http://automationpractice.com/index.php?id_product=3&controller=product",
 orderCartUrl:"http://automationpractice.com/index.php?controller=order",
}
